### ISSUE TITLE
Remove Outliers

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/rescue-chicago#11]
There's some crazy data that we ingest from PetFinder - like dogs that have apparently been up for adoption for 10+ years. We'll want to remove any obviously wrong data from our database, so that it doesn't lead to misleading conclusion in the dashboards.

Some ideas for analysis to help inform outlier removal:
- [ ] Plot of typical LOS by posted date (thought being that maybe older postings have less reliable data)
- [ ] Histogram of LOS data (thought being that maybe there's some process to automatically remove dogs after some amount of time, e.g. maybe their postings "expire")
- [x] Boxplot of LOS by organization (thought being that maybe some organizations are better or worse than others at being diligent about their data)

**Comment by Jared-Kunhart** [comment]
Data from more cities is being pulled in and the outliers are becoming more apparent. Currently on the Breed Trends by LoS out of 20 breeds - 7 of those breeds are under a count of 5.

**Comment by Jared-Kunhart** [comment]
Made a branch for this issue - 11-remove-outliers

**Comment by Jared-Kunhart** [comment]
Dynamic slider gives filter outliers to the user. In addition, Jhen has also filtered outliers in the model preprocessing.
