### ISSUE TITLE
Adoptability Model Improvements

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/rescue-chicago#26]
Feature Selection
- [x] Descriptive stats on color, breed to learn which are correlated to LOS
- [x] Test for multicollinearity between features

Data Quality
- [x] Remove outliers (based on LOS)

Model Evaluation
- [x] Add additional evaluation metrics

**Comment by JJD129** [comment]
**Feature selection:** 
<img width="789" alt="Screenshot 2023-05-25 at 4 07 42 PM" src="https://github.com/Code-For-Chicago/rescue-chicago/assets/49170325/5b72f005-310e-4e2c-ba02-638b34e3e6b0">
**Data Quality**: uses a z-score method
<img width="740" alt="Screenshot 2023-05-25 at 4 09 05 PM" src="https://github.com/Code-For-Chicago/rescue-chicago/assets/49170325/c0a44784-dea3-4484-9ff4-c3d54d7634eb">
**Model Evaluation Metrics**: uses R^2, MSE, and MAE
