### ISSUE TITLE
Quality Control on House Trained

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/rescue-chicago#5]
- [x] Make sure that nulls aren't turning into False's
- [x] #38

**Comment by JayDrojas** [comment]
Email has been sent. Waiting on reply.

**Comment by JayDrojas** [comment]
# Reply from Petfinder 

Petfinder has stated that the question for house trained is either a true or a false. No data on house trained will ever be null.
See below for screenshots of the email.

![IMG_6479](https://github.com/Code-For-Chicago/rescue-chicago/assets/86801740/def61021-142b-4bc6-9622-ff68613fc97a)

![IMG_6481](https://github.com/Code-For-Chicago/rescue-chicago/assets/86801740/2dc5bfce-6fa8-4fad-aeed-ac8e33520c6d)
