### ISSUE TITLE
Research PetFinder Resources

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/rescue-chicago#7]
Some datasets from PetFinder have already been curated and used for other applications like Kaggle competitions.

This ticket is to research prior competitions or community projects that have used PetFinder data, and see if anything from this could be useful. For example, there might be an existing dataset we could pull from, ideas of how to engineer features, etc.

One starting place could be [this](https://www.kaggle.com/competitions/petfinder-adoption-prediction/overview) Kaggle competition, or [this](https://www.tensorflow.org/datasets/catalog/pet_finder) corresponding dataset in TensorFlow.

You can document your findings either in this GitHub repo, or our shared Google Drive

**Comment by Jared-Kunhart** [comment]
Some examples in https://www.kaggle.com/competitions/petfinder-adoption-prediction/code

Dog vs Cat adoption speed -
https://www.kaggle.com/code/ananyasood02/petfinder-my-detailed-eda-and-xgboost-baseline

Including anymore datasets or features from these resources would be interesting but the timeline would push the project well beyond scope.
